from pathlib import Path
import pandas as pd
from antibiotic_env import read_data, compute_metrics, plot_spatiotemporal, plot_risk_matrix, plot_exceedance

def run(input_path, outdir='outputs'):
    outdir = Path(outdir); outdir.mkdir(parents=True, exist_ok=True)
    print(f"[INFO] Input: {input_path}")
    print(f"[INFO] Outdir: {outdir}")
    df = read_data(input_path)
    df_all, per_site, exceed = compute_metrics(df)
    plot_spatiotemporal(df_all, outdir)
    plot_risk_matrix(df_all, outdir)
    plot_exceedance(exceed, outdir)
    with pd.ExcelWriter(outdir / 'outputs.xlsx') as xw:
        df_all.to_excel(xw, index=False, sheet_name='records')
        per_site.to_excel(xw, index=False, sheet_name='site_metrics')
        exceed.to_excel(xw, index=False, sheet_name='exceedance')
    (outdir / 'outputs_report.md').write_text('# AntibioticEnv Outputs\n\nGenerated by AntibioticEnv System v1.1.', encoding='utf-8')
    print('[DONE] Generated outputs in', outdir)

if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        print('Usage: python run_all.py <data.csv|data.xlsx>')
    else:
        run(sys.argv[1])
